sampleData = 'TGAGCTGTTAGCCCGAGCTGTGTCCGCTGCGAGCTGTTTGTATGAGCTGTAGAGCTGTGAGCTGTCGAGCTGTATGAGCTGTACCCAGAGCTGTGAGCTGTTAGTCAAGAGCTGTGAGCTGTCGATAGAGCTGTTGGAGCTGTCTGGGAGCTGTTCGTAAACCCGAGCTGTATAGAGCTGTGACAGTGGAGCTGTCGTACGAGCTGTCAGGGAGCTGTGAGCTGTGAGCTGTAGAGCTGTGAGCTGTGTCCGAGCTGTACAGAGCTGTGAGCTGTAGGACGAGCTGTCTCACGAGCTGTTTAGAGCTGTGAAGAGCTGTACATTAGAGCTGTGAGCTGTCCCGAGCTGTCCTGTATCAAGAGCTGTGGAGCTGTATGGAGCTGTGAGCTGTGTGGAGCTGTTGAGCTGTGAGCTGTAAAGGGGCGAGCTGTCAATCGAGCTGTGGGTGAGCTGTTGAGCTGTGCGGAGCTGTGAGCTGTTGAGCTGTACGAGCTGTCTTAGAGCTGTGTTAGAGCTGTGAGCTGTTAGAGCTGTCCTGTTGAGCTGTTGAGCTGTTAGGAGCTGTTCAATCAGAGCTGTTATGTTGAGCTGTAGGAGCTGTGACTATTTGAGCTGTCGGGGAGCTGTATTGAGCTGTAGACTGAGCTGTGAGCTGTTGGCGAGCTGTCTCAGCGAGCTGTGAGCTGTGAGCTGTCTTTTATGAGCTGTCAGGAGCTGTTGAGCTGTAGAGCTGTGAGTTGAGCTGTCTGGTCGAGGAGCTGTCCAGCTTGAGGCCCCGGAGAGCTGTGAGCTGTATCAGAATTCTGAGCTGTCGATGAGCTGTGAGCTGTTAGGAGCTGTGGAGCTGTCCAGGAGCTGTGATGTAAAGGAGAGCTGTTGAGCTGTCGAGCTGTGGAGCTGTGGGAGCTGTCTGCAGACGGAGCTGT'
target = 'GAGCTGTGA'

def substringLocation(substring,data):
    count = []
    start = 0
    while start < len(data):
        pos = data.find(substring, start)
        if pos != -1:
            start = pos + 1
            count.append(start)
        else:
            break
    print(count)
    return count

substringLocation(target,sampleData)
